Sprint 1/step 2
Jenyadio/react-burger pull request #2
Opened 2023-05-05 06:56 UTC by Jenyadio

Здравствуйте! Отправляю пул-реквест на вторую часть работы. Спасибо!

2023-05-05 19:52 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сделали отписку от слушателя событий
- Реализовали закрытие по ESC
- Url записали в константу 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- Распишите тип ингредиента и используйте везде где он принимается в качестве пропсов
- Допишите propTypes у некоторых компонентов

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/app-main/app-main.jsx
> +    const getIngredients = () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/app-main/app-main.jsx
> +      .then(res => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  data: PropTypes.array.isRequired,
**Необходимо исправить**
Сейчас получается, что под `data` может прийти массив любого содержания, но это не так. Необходимо полностью расписать тип ингредиента со всеми его полями (чтобы не дублировать код - сделайте это в отдельном файле) и использовать во всех подобных местах. Вам помогут в этом функции propTypes `arrayOf` и `shape`.

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      document.removeEventListener("keydown", escModal, false);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +        <article>
**можно лучше**
Тут тег article не совсем подходит
`https://htmlacademy.ru/blog/html-tags/article`

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/order-total/order-total.jsx
> +    {props.active &&
**Необходимо исправить**
в `propTypes` не указан проп `active `

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
**Необходимо исправить**
`children ` так же необходимо указывать в `propTypes`

2023-05-05 19:52 UTC, andryxxa93 commented on src/components/item/item.jsx
> +function Item(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-05-06 12:17 UTC, Jenyadio commented on src/components/app-main/app-main.jsx
> +    const getIngredients = () => {
Спасибо, поправила, но не уверена, что совсем правильно

2023-05-06 12:17 UTC, Jenyadio commented on src/components/app-main/app-main.jsx
> +      .then(res => res.json())
Поправила

2023-05-06 12:17 UTC, Jenyadio commented on src/components/burger-constructor/burger-constructor.jsx
> +  data: PropTypes.array.isRequired,
Поправила

2023-05-06 12:18 UTC, Jenyadio commented on src/components/modal/modal.jsx
> +        <article>
Поменяла на section

2023-05-06 12:18 UTC, Jenyadio commented on src/components/order-total/order-total.jsx
> +    {props.active &&
Спасибо, поправила

2023-05-06 12:18 UTC, Jenyadio commented on src/components/modal/modal.jsx
> +Modal.propTypes = {
Поправила

2023-05-06 12:18 UTC, Jenyadio commented on src/components/item/item.jsx
> +function Item(props) {
Спасибо, поправила

2023-05-07 06:27 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

2023-05-07 13:56 UTC, merged