Sprint 2/step 2
Jenyadio/react-burger pull request #4
Opened 2023-05-26 17:17 UTC by Jenyadio

Здравствуйте! Отправляю на проверку 2-ую часть 2-го спринта. 
Спасибо! :)

2023-05-26 18:40 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Для запросов созданы все необходимые типы экшенов
- Хорошо разобрались с `redux` 
- Хорошая структура файлов хранилища

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Экшен `GET_ORDER_FAILED` не срабатывает при ошибке во время запроса на номер заказа. Вам необходимо поместить его вызов в обработчик `catch` 
- для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный uuid (Вам нужно его генерировать во время сброса в зону DnD). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в `key` будет уже просто `key={ item.uuid }`
- У вас в хранилище много дублируется информация. Например в `burgerIngredients` содержатся все ингредиенты, но так же `constructorIngredients` в поле `ingredients` содержаться они же. Дублировать информацию не стоит, особенно в хранилище.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-26 18:40 UTC, andryxxa93 commented on src/components/order-details/order-details.jsx
> +  const number = useSelector((store) => store.orderDetails.orderNumber);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-26 18:40 UTC, andryxxa93 commented on src/utils/selectors.js
> +export const totalPriceSelector = state => {
**Можно лучше**
Вычислять стоимость лучше в компоненте, а не в селекторе. Селекторы обычно простые функции, обеспечивающие доступ к нужному полю - без каких-то дополнительных операций.

2023-05-27 16:41 UTC, Jenyadio commented on src/components/order-details/order-details.jsx
> +  const number = useSelector((store) => store.orderDetails.orderNumber);
Спасибо, посмотрела, поправила!)

2023-05-27 16:41 UTC, Jenyadio commented on src/utils/selectors.js
> +export const totalPriceSelector = state => {
Спасибо, поправила!

2023-05-28 06:59 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-28 07:38 UTC, merged