Sprint 4/step 1
Jenyadio/react-burger pull request #6
Opened 2023-06-28 12:05 UTC by Jenyadio

Здравствуйте! Отправляю на проверку работу по 4-му спринту.
Спасибо!

2023-06-28 13:49 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу вы должно типизировать все утилитарные функции, в том числен и запросы к серверу.
  Типизировать запросы к серверу можно следующим образом:

```ts
type TServerResponse<T> = {
  success: boolean;
} & T;

type TIngredientsResponse = TServerResponse<{
  data: TIngredient[];
}>;

const checkResponse = <T>(res: Response): Promise<T> => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};

const request = async <T>(endpoint: string, options?: RequestInit): Promise<T> => {
  return fetch(`${NORMA_API}${endpoint}`, options).then(res => checkResponse<T>(res));
};

export const getIngredients = () => {
  return request<TIngredientsResponse>('/ingredients');
};
```

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-06-28 13:49 UTC, ArslanMustafin commented on src/components/item/item.tsx
> +}
**Надо исправить?**

Тут у вас описаны поля ингредиента, лучше будет вынести это тип в папку `types/ingredient.ts` и переиспользовать

2023-06-28 13:49 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +const request = async (endpoint: string, options?: RequestInit) => {
**Надо исправить:**

По чек-листу вы должно типизировать все утилитарные функции, в том числен и запросы к серверу.
Типизировать запросы к серверу можно следующим образом:

```ts
type TServerResponse<T> = {
  success: boolean;
} & T;

type TIngredientsResponse = TServerResponse<{
  data: TIngredient[];
}>;

const checkResponse = <T>(res: Response): Promise<T> => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};

const request = async <T>(endpoint: string, options?: RequestInit): Promise<T> => {
  return fetch(`${NORMA_API}${endpoint}`, options).then(res => checkResponse<T>(res));
};

export const getIngredients = () => {
  return request<TIngredientsResponse>('/ingredients');
};
```

2023-06-29 10:37 UTC, Jenyadio commented on src/components/item/item.tsx
> +}
Спасибо, поправила

2023-06-29 10:38 UTC, Jenyadio commented on src/utils/burger-api.ts
> +const request = async (endpoint: string, options?: RequestInit) => {
Спасибо, поправила

2023-06-29 16:58 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-03 09:10 UTC, merged