Sprint 6/step 1
Jenyadio/react-burger pull request #8
Opened 2023-07-27 11:53 UTC by Jenyadio

Здравствуйте! Отправляю на проверку работу по 6-му спринту.
Спасибо!

2023-07-27 13:32 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты (46 шт) проходят успешно
- Все Cypress тесты проходят успешно
- В readme есть ссылка на проект.

### **Есть 1 замечание, которое нужно исправить:**

- Отметил замечание в коде;

### **Сделает код лучше:**

- Чтобы проверить процент покрытия тестами всех файлов, используйте команду `react-scripts test --coverage --watchAll`

2023-07-27 13:32 UTC, ArslanMustafin commented on cypress/e2e/spec.cy.ts
> +const url = "http://localhost:3000/";
**Надо исправить:**

Вынесите базовый адрес сервера в константу и переиспользуйте.

Константы принято записывать в `UPPER_CASE`, но тут лучше использовать встроенные переменные, которые настраиваются через конфиг.

<https://docs.cypress.io/guides/references/configuration#Intelligent-Code-Completion>

2023-07-27 13:32 UTC, ArslanMustafin commented on cypress/e2e/spec.cy.ts
> +    cy.get("button").contains("Войти").click();
**Можно лучше:**

здесь и далее.

лучше все таки использовать моки.

https://docs.cypress.io/api/commands/intercept

2023-07-27 17:31 UTC, Jenyadio commented on cypress/e2e/spec.cy.ts
> +const url = "http://localhost:3000/";
Спасибо, исправила

2023-07-27 17:31 UTC, Jenyadio commented on cypress/e2e/spec.cy.ts
> +    cy.get("button").contains("Войти").click();
Спасибо, разберусь с этим на днях

2023-07-28 08:02 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2023-07-30 07:48 UTC, merged